<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <!-- Don't auto-include .cs files from ItemTemplates -->
    <EnableDefaultCompileItems>true</EnableDefaultCompileItems>
  </PropertyGroup>
  <ItemGroup>
    <Content Remove="Images\Logo.png" />
    <Content Remove="Images\Logo32x32.png" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.VisualStudio.Extensibility.Sdk" Version="17.14.40608" PrivateAssets="all" />
    <PackageReference Include="Microsoft.VisualStudio.Extensibility.Build" Version="17.14.40608" PrivateAssets="all" />
    <PackageReference Include="Microsoft.CodeAnalysis.Workspaces.Common" Version="4.11.0" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp.Workspaces" Version="4.11.0" />
  </ItemGroup>

  <!-- Exclude ItemTemplates from compilation -->

  <!-- Include ItemTemplates as content to copy to output -->
  <ItemGroup>
    <None Remove="Monikers.imagemanifest" />
    <None Remove="Overview.md" />
  </ItemGroup>
  <ItemGroup>
    <content Include="Monikers.imagemanifest">
      <IncludeInVSIX>true</IncludeInVSIX>
    </content>
    <Content Include="Overview.md" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Dialogs\AddLiquidErrorPageDialogControl.xaml">
      <Generator>MSBuild:Compile</Generator>
    </EmbeddedResource>
    <EmbeddedResource Include="Dialogs\AddLiquidPageDialogControl.xaml">
      <Generator>MSBuild:Compile</Generator>
    </EmbeddedResource>
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Images\Logo.png" />
    <Resource Include="Images\Logo32x32.png" />
  </ItemGroup>
</Project>
