<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<OutputType>Exe</OutputType>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\Kinetq.LiquidPages.GenHTTP\Kinetq.LiquidPages.GenHTTP.csproj" />
	</ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="**\*.liquid" />
  </ItemGroup>

	<ItemGroup>
		<Content Include="Static\**\*">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
			<ExcludeFromSingleFile>true</ExcludeFromSingleFile>
			<CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
		</Content>
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="GenHTTP.Core" Version="10.5.3" />
		<PackageReference Include="GenHTTP.Modules.IO" Version="10.5.3" />
		<PackageReference Include="Microsoft.Extensions.Logging.Console" Version="10.0.9" />
	</ItemGroup>

</Project>
