<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="EmbedIO" Version="3.5.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Kinetq.LiquidPages\Kinetq.LiquidPages.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <Version>0.0.5</Version>
    <RepositoryUrl>https://github.com/kinetq/liquid-pages</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <Description>This is a library provides a web module to add liquid middleware to EmbedIO.</Description>
    <Authors>Sammi Sinno</Authors>
  </PropertyGroup>

</Project>
