name: CI

on: 
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Setup Dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '9.0.x'
          
    - name: Restore Solution
      run: dotnet restore Kinetq.LiquidPages.sln
      
    - name: Build Solution
      run: dotnet build Kinetq.LiquidPages.sln  
      
    - name: Test Solution
      run: dotnet test Kinetq.LiquidPages.sln
      
    - name: Publish Visual Studio Extension
      uses: cezarypiatek/VsixPublisherAction@1.0
      with:
        extension-file: src/Kinetq.LiquidPages.Extension/bin/Release/Kinetq.LiquidPages.Extension.vsix
        publish-manifest-file: src/Kinetq.LiquidPages.Extension/publishManifest.json
        personal-access-code: ${{secrets.MARKETPLACE_PAT}}
      
    - name: Publish Liquid Simple Server
      uses: alirezanet/publish-nuget@v3.0.0
      with:
          PROJECT_FILE_PATH: src/Kinetq.LiquidPages/Kinetq.LiquidPages.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          INCLUDE_SYMBOLS: true
          
    - name: Publish Liquid EmbedIO Module
      uses: alirezanet/publish-nuget@v3.0.0
      with:
          PROJECT_FILE_PATH: src/Kinetq.LiquidPages.EmbedIO/Kinetq.LiquidPages.EmbedIO.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          INCLUDE_SYMBOLS: true

    - name: Publish Liquid Templates
      uses: alirezanet/publish-nuget@v3.0.0
      with:
          PROJECT_FILE_PATH: src/Kinetq.LiquidPages.Templates/Kinetq.LiquidPages.Templates.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          INCLUDE_SYMBOLS: true

